[source]
# Path to the source that contains the CV's data, can be json, toml, or yml/yaml
path = "./source.yml"

[template]
# Path or URL to the html file to render the source data, must use Tera's syntax
source = "./render.html"

[output]
# The path, doesn't include extension
path = "./test-cv"
# The output type(s): pdf or html
types = ["html", "pdf"]
